### ISSUE TITLE
easyfmridata, GPUHA, CV: error at hyperalignment

### ISSUE THREAD

**Issue by vitruvi** [easyfmri/easyfmri#3]
I have generated CV folds. Now I get an error as below on GPUHA and folds 1-19, default selections:
"ERROR: Train, Reshape problem for Fold 7, Shape: (366, 19174)" (GPUHA, DS007-stopvocal_fold[1-19])
Likewise, error at fold 4 for stopmanual CV [1-20].

Can you help me about this?

Thanks for your answers so far.

One follow up question regarding SSTL:
in equation (2), P is calculated with SVD variables but the form X(XX'+eps*I)X' do not match in dimensions.
The same applied for R variable, (XX'+eps*I)X'G. 

i.e. X in TxV, I in TxT, G in Txk and
(XX'+eps*I)X' is [TxT][VxT.]

This does not cause a problem for calculation of G^d (SVD variables are used), however we need R for transforming data during classification, XRW. Should I recalculate SVD during train/test and use PGW instead of XRW?

Is there a correction for this? Please correct me if I am misinterpreting.

**Comment by myousefnezhad** [comment]
You have to temporarily align your data before running the cross-validation.

Feature Analysis -> Feature Design -> Temporal Alignment -> Temporal alignment with intersection strategy

Is one of the solutions.

**Comment by vitruvi** [comment]
I could not find details about "Temporal alignment with intersection strategy". Can you explain how it matches timepoints? Does it add/remove trailing or leading timepoints?
